# Site Settings
title: Nguyen Van Chung Resume
description: "Curriculum Vitae of chung@agiletech.vn"
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nguyen Van Chung
tagline: Solution Architect
pic: https://github.com/tubackkhoa.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "With more than 9 years of work experience in various positions, various technologies, I would like to build awesome systems.
I love coding, studing new technologies and having time with my family.
<br>
I believe that every problem has its own solution.
<br>
You can view more about <a href='http://agiletech.vn' target='_blank'>Agiletech Viet Nam</a>."

#sidebar links
email: chung@agiletech.vn
phone: +84 989 746 579
website: agiletech.vn #do not add http://
linkedin: chung-nguyen-6756a6160
github: chungnv
twitter: '@chungnv'

#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
